# Generated by Django 5.1.4 on 2024-12-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('skills', models.TextField()),
                ('company', models.CharField(max_length=255)),
                ('salary_from', models.FloatField(blank=True, null=True)),
                ('salary_to', models.FloatField(blank=True, null=True)),
                ('salary_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('region', models.CharField(max_length=255)),
                ('publication_date', models.DateField()),
            ],
        ),
    ]
